baseURL: https://deliastephens.github.io/

title: delia stephens
paginate: 
  pagerSize: 5
theme:
  - charlolamode
  - hugo-shortcode-gallery 

menu:
  main:
    - name: aeroastro
      url: /aeroastro/
      weight: 20
    - name: visual
      url: /visual/
      weight: 30
    - name: notes
      url: /notes/
      weight: 40
    - name: misc
      url: /misc/
      weight: 50

params:
  author: Delia Stephens
  
  defaultTheme: auto
  ShowShareButtons: false
  ShowToc: false
  
  profileMode:
    enabled: true
    title: Delia Stephens
    description: |
      Hi! I'm Delia. I recently graduated with a combined SB/SM from MIT AeroAstro, where my research focused on [developing flexible policies for decision-making under uncertainty](https://dspace.mit.edu/bitstream/handle/1721.1/144709/Stephens-delias-SM-AeroAstro-2022-thesis.pdf?sequence=1&isAllowed=y). Right now, I'm a First Lieutenant in the United States Air Force.

      I like to keep myself busy by [riding (and fixing) bicycles](/misc/spokes/), [shooting photos](/visual/), and [making useless things](/misc/bike-bottle-cage/). In the past, I've built a rocket that carries a GoPro, biked across the country, and taken a lot of notes.
    imageUrl: "/images/profile.jpg"
    imageTitle: Delia Stephens

    # buttons:
      

  socialIcons:
    - name: github
      url: "https://github.com/deliastephens"
    - name: linkedin
      url: "https://www.linkedin.com/in/delia-stephens-909853147/"

  assets:
    favicon: "/images/favicon.ico"
    favicon16x16: "/images/favicon-16x16.png"
    favicon32x32: "/images/favicon-32x32.png"
    apple_touch_icon: "/images/apple-touch-icon.png"
    safari_pinned_tab: "/images/apple-touch-icon.png"

      

      
